interface SiteType {
  [site: string]: string;
}

export const siteName: SiteType = {
  kakao: '카카오',
  woowa: '우아한형제들',
  banksalad: '뱅크샐러드',
  kurly: '마켓컬리',
  watcha: '왓챠',
  daangn: '당근마켓',
  wanted: '원티드',
  line: '라인',
  ridi: '리디북스',
  '44bit': '44BIT',
  toss: '토스',
  zigbang: '직방',
  yanolja: '야놀자',
  musinsa: '무신사',
  kakaoenterprise: '카카오엔터프라이즈',
  '11st': '11번가',
  brandi: '브랜디',
  idus: '아이디어스',
  bbros: '비브로스',
  kakaoent: '카카오엔터테인먼트',
  hwahae: '화해',
  class101: '클래스101',
  spoon: '스푼',
  soomgo: '숨고',
  remember: '드라마앤컴퍼니',
  liner: '라이너',

  athenaslab: '아테나스랩',
  ssg: '신세계',
  zum: 'ZUM',
  petfriends: '펫프렌즈',
  opgg: 'OP.GG',
  kimjeonghwan: '김정환블로그',
  toast: 'TOAST',
  jojoldu: '기억보단 기록을',
  yogiyo: '요기요',
  hyperconnect: '하이퍼커넥트',
  '29cm': '29CM',
};
